### ISSUE TITLE
Ubuntu 18.04 / 20.04 support?

### ISSUE THREAD

**Issue by TheSwede86** [aws-quickstart/quickstart-linux-utilities#25]
Hi,

Sorry if this is something that is quite clear but came across this project through this post:
https://aws.amazon.com/blogs/infrastructure-and-automation/introduction-to-quickstart-linux-utilities/
and there it says support for Ubuntu 18.04 is coming soon but it was last updated 2 Oct 2019.

I guess since I see "ci/ubuntu.json" which mentions 18.04 and also "ci/ubuntu20.json" that both 18.04 and 20.04 are supported now? However "quickstart-cfn-tools.source" just mention 20.04.

I tried looking in the readme or find further documentation but was unable to. 

Thanks for your great work!

**Comment by lschierer** [comment]
I am having trouble with these scripts on Ubuntu 20.04, 

```
Installing collected packages: pip, setuptools, wheel
Successfully installed pip-20.3.4 setuptools-44.1.1 wheel-0.37.1
WARNING: You are using pip version 20.3.4; however, version 21.3.1 is available.
You should consider upgrading via the '/usr/bin/python2.7 -m pip install --upgrade pip' command.
+ sudo pip2 install https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Collecting https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz
  Downloading https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz (465 kB)
Collecting python-daemon<2.0,>=1.5.2
  Downloading python-daemon-1.6.1.tar.gz (47 kB)
Collecting pystache>=0.4.0
  Downloading pystache-0.6.0.tar.gz (78 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python2.7 /usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpbcCvH8
       cwd: /tmp/pip-install-rNzEk6/pystache
  Complete output (17 lines):
  Traceback (most recent call last):
    File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/usr/local/lib/python2.7/dist-packages/setuptools/build_meta.py", line 146, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/usr/local/lib/python2.7/dist-packages/setuptools/build_meta.py", line 127, in _get_build_requires
      self.run_setup()
    File "/usr/local/lib/python2.7/dist-packages/setuptools/build_meta.py", line 142, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 183
      command = f"pandoc -f markdown-smart --write=rst --output={rst_temp_path} {md_path}"
                                                                                         ^
  SyntaxError: invalid syntax
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python2.7 /usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpbcCvH8 Check the logs for full command output.
```

seems to be the relevant section of cloud-init-output.log which is triggered by the qs_bootstrap_pip command.  This seems to be a prereq for the qs_aws-cfn-bootstrap command, and so is misleadingly important.

**Comment by tlindsay42** [comment]
Closing in favor of #26
